connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.catalog-name=views
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://views-db:5432/views_meta
iceberg.jdbc-catalog.connection-user=trino
iceberg.jdbc-catalog.connection-password=trino
iceberg.jdbc-catalog.default-warehouse-dir=file:///var/lib/trino/iceberg-warehouse
fs.native-local.enabled=true